tab_spaces = 4
imports_granularity = "One"
group_imports = "One"
use_field_init_shorthand = true
reorder_impl_items = true
wrap_comments = true
normalize_comments = true
format_strings = true
format_macro_matchers = true
format_code_in_doc_comments = true
condense_wildcard_suffixes = true
